apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-sdtt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-sdtt
    app.kubernetes.io/part-of: quarkus
  name: devfile-sample-code-with-quarkus-sdtt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-sdtt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-sdtt
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-aeiq-tenant/quarkus/devfile-sample-code-with-quarkus-sdtt@sha256:4e8b938e5c85a27f7f5327a507b4d3883f30e7a9ecf347b783f07123962833a7
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
